--Tạo bảng 
CREATE TABLE TIKI_BOOK (
	ID BIGINT PRIMARY KEY ,
	SKU BIGINT ,
	BOOK_NAME VARCHAR(500) ,
	ORIGIN_PRICE INT CHECK (ORIGIN_PRICE >= 0),
	DISCOUNT_RATE INT CHECK (DISCOUNT_RATE >= 0) ,
	DISCOUNT INT CHECK (DISCOUNT >= 0) ,
	PRICE INT CHECK (PRICE >= 0) ,
	DESCRIPTION VARCHAR(60000) ,
	QUANTITY_SOLD INT CHECK (QUANTITY_SOLD >= 0) ,
	CATEGORIES VARCHAR(100) ,
	INFOR_RETURN VARCHAR(100) ,
	GIFT_ITEM_TITLE  VARCHAR(20) ,
	CHECK(ORIGIN_PRICE >= PRICE)
);

DROP TABLE TIKI_BOOK ;

--Tối ưu truy vẫn 
CREATE UNIQUE INDEX indx_book_sku ON TIKI_BOOK(SKU)  

CREATE INDEX indx_book_categories ON TIKI_BOOK(CATEGORIES)

CREATE INDEX indx_book_price ON TIKI_BOOK(PRICE)

CREATE INDEX indx_book_quantity_sold ON TIKI_BOOK(QUANTITY_SOLD)

--Tối ưu truy vấn khi dùng LIKE hoặc ILIKE
CREATE EXTENSION IF NOT EXISTS pg_trgm 
CREATE INDEX indx_book_name_trgm ON TIKI_BOOK USING gin (BOOK_NAME gin_trgm_ops) 

SELECT * FROM TIKI_BOOK 

--Các truy vấn phân tích

-- TOP sách bán chạy nhất
SELECT BOOK_NAME ,
	   CATEGORIES ,
	   QUANTITY_SOLD ,
	   PRICE ,
	   (QUANTITY_SOLD::BIGINT * PRICE::BIGINT) AS REVENUE
FROM TIKI_BOOK 
ORDER BY QUANTITY_SOLD DESC
LIMIT 10 


--TÔNG SỐ DANH MỤC PHỔ BIẾN
SELECT CATEGORIES ,
	   COUNT(*) AS TOTAL_CR
FROM TIKI_BOOK
GROUP BY CATEGORIES 
ORDER BY TOTAL_CR DESC 

--TOP DANH MỤC CÓ DOANH THU CAO NHÂT 
SELECT CATEGORIES ,
	   SUM(PRICE::BIGINT * QUANTITY_SOLD::BIGINT) AS TOTAL_REVENUE,
	   COUNT(*) AS TOTAL_CR ,
	   ROUND(AVG(PRICE) , 0)  AS AVG_PRICE
FROM TIKI_BOOK 
GROUP BY CATEGORIES 
ORDER BY TOTAL_REVENUE DESC 

--TOP CÁC QUYỂN SÁCH CÓ GIÁ CAO NHẤT TRONG MỖI DANH MỤC NẰM TRONG TOP DOANH THU CAO NHẤT
SELECT TK.CATEGORIES ,
	   TK.PRICE  
FROM TIKI_BOOK TK
WHERE  1 = 1
  AND TK.CATEGORIES IN (SELECT CATEGORIES 
						FROM TIKI_BOOK 
						GROUP BY CATEGORIES
						ORDER BY SUM(PRICE::BIGINT * QUANTITY_SOLD::BIGINT) DESC) 
  AND TK.PRICE IN (SELECT T.PRICE 
  				   FROM TIKI_BOOK T
				   WHERE T.CATEGORIES = TK.CATEGORIES
				   ORDER BY PRICE DESC)

--Phân tích Execution Plan
EXPLAIN ANALYZE
SELECT *
FROM TIKI_BOOK
WHERE CATEGORIES = 'Kinh Dịch Học'
  AND PRICE BETWEEN 100000 AND 300000
